name: cta4j Back-end CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build with Maven
        env:
          SECRET_ID: foo
        run: mvn -B package -DskipTests --file pom.xml
      - name: Run Tests
        run: mvn test
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-artifacts
          path: target/*.jar
